# Generated by Django 5.1 on 2025-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
