# Generated by Django 5.1 on 2025-04-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_rename_notes_expense_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
